[[constraint]]
  name = "github.com/cloudevents/sdk-go"
  #version = "0.6.0"
  revision = "001f4eefdc635dd230bffd7d7f7f8842803e4c9f"
  source = "github.com/n3wscott/sdk-go"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "pack.ag/amqp"
  version = "0.11.0"

[prune]
  go-tests = true
  unused-packages = true
