apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: graph
spec:
  template:
    spec:
      serviceAccountName: knap
      containers:
        - image: github.com/n3wscott/knap/cmd/graph/
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
