apiVersion: apps/v1
kind: Deployment
metadata:
  name: <NAME>-sink
spec:
  selector:
    matchLabels:
      app: <NAME>-sink
  template:
    metadata:
      labels:
        app: <NAME>-sink
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: user-container
        image: github.com/n3wscott/kpax/amqp/cmd/sink
        env:
          - name: AMQP_SERVER
            valueFrom:
              secretKeyRef:
                name: <NAME>-amqp
                key: server
          - name: AMQP_QUEUE
            valueFrom:
              secretKeyRef:
                name: <NAME>-amqp
                key: queue
          - name: AMQP_ACCESS_KEY_NAME
            valueFrom:
              secretKeyRef:
                name: <NAME>-amqp
                key: access_key_name
          - name: AMQP_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: <NAME>-amqp
                key: access_key
          - name: SINK_ACCESS_KEY_NAME
            valueFrom:
              secretKeyRef:
                name: <NAME>-amqp
                key: sink_access_key_name
          - name: SINK_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: <NAME>-amqp
                key: sink_access_key
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: <name>-sink
spec:
  selector:
    app: <name>-sink
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080