apiVersion: v1
kind: Secret
metadata:
  name: <NAME>-amqp
type: Opaque
stringData:
  access_key_name: <access_key_name>
  access_key: <access_key>
  server: <server>
  queue: <queue>
  sink_access_key_name: <sink_access_key_name>
  sink_access_key: <sink_access_key>
